- name: configure yum erlang repo
  ansible.builtin.shell: curl -s https://packagecloud.io/install/repositories/rabbitmq/erlang/script.rpm.sh | bash
- name: configure yumm repo for rabbitmq
  ansible.builtin.shell: curl -s https://packagecloud.io/install/repositories/rabbitmq/rabbitmq-server/script.rpm.sh | bash
- name: install rabbitmq
  ansible.builtin.dnf:
    name: rabbitmq-server
    state: present
- name: start and enable rabbitmq
  ansible.builtin.service:
    name: rabbitmq-server
    state: restarted
    enabled: yes

- name: rabbitmq user and set_permissions
  community.rabbitmq.rabbitmq_user:
  user: "{{ lookup('aws_ssm', '/roboshop/{{env}}/rabbitmq_user', region='us-east-1' , decrypt=True ) }}"
  password: "{{ lookup('aws_ssm', '/roboshop/{{env}}/rabbitmq_password', region='us-east-1' , decrypt=True ) }}"
  vhost: /
  configure_priv: .*
  read_priv: .*
  write_priv: .*
  state: present

# - name: creating rabbitmq user
#   ansible.builtin.command: rabbitmqctl add_user roboshop roboshop123
# - name: set permission
#   ansible.builtin.command: rabbitmqctl set_permissions -p / roboshop ".*" ".*" ".*"
# will take values from ssm parameters of type securestring